// reportFile.js
import { Readable } from "stream";

/**
 * Build a downloadable text report from the LLM answer.
 * You can customize formatting here without touching the bot logic.
 */
export function buildReportText(rawAnswer, meta = {}) {
  const { name, age } = meta;

  let header = "MedEdu AI Doctor – Educational Health Report\n";
  header += "============================================\n\n";

  if (name || age) {
    header += "Patient Details:\n";
    if (name) header += `• Name: ${name}\n`;
    if (age) header += `• Age: ${age}\n`;
    header += "\n";
  }

  const footer =
    "\n\n--------------------------------------------\n" +
    "Generated by MedEdu AI Doctor (educational only).\n" +
    "This is NOT a medical diagnosis. Always consult a licensed physician.\n";

  return header + rawAnswer + footer;
}

/**
 * Create a stream suitable for bot.sendDocument from a text report.
 */
export function reportTextToStream(reportText) {
  return Readable.from([reportText]);
}
